# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('sq_meters', models.PositiveIntegerField()),
                ('kitchen_sq_meters', models.PositiveSmallIntegerField()),
                ('nr_bedrooms', models.PositiveSmallIntegerField()),
                ('nr_bathrooms', models.PositiveSmallIntegerField()),
                ('nr_floors', models.PositiveSmallIntegerField(default=1)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('house_color_outside', models.CharField(max_length=20)),
                ('distance_to_nearest_kindergarten', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_to_nearest_school', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_to_nearest_hospital', models.PositiveIntegerField(blank=True, null=True)),
                ('has_cellar', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_garage', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='houses.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
